//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabalhoPratico.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrabalhoPratico.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre.
        /// </summary>
        internal static string BUTTON_ABOUT {
            get {
                return ResourceManager.GetString("BUTTON_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestão de Artigos.
        /// </summary>
        internal static string BUTTON_ARTIGOS {
            get {
                return ResourceManager.GetString("BUTTON_ARTIGOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string BUTTON_ELIMINAR {
            get {
                return ResourceManager.GetString("BUTTON_ELIMINAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravar.
        /// </summary>
        internal static string BUTTON_GRAVAR {
            get {
                return ResourceManager.GetString("BUTTON_GRAVAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listar Artigos.
        /// </summary>
        internal static string BUTTON_LISTAR {
            get {
                return ResourceManager.GetString("BUTTON_LISTAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo.
        /// </summary>
        internal static string BUTTON_NOVO {
            get {
                return ResourceManager.GetString("BUTTON_NOVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string BUTTON_OBTER {
            get {
                return ResourceManager.GetString("BUTTON_OBTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        internal static string BUTTON_SAIR {
            get {
                return ResourceManager.GetString("BUTTON_SAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id inválido.
        /// </summary>
        internal static string CODIGO_ERRO_INVALIDO {
            get {
                return ResourceManager.GetString("CODIGO_ERRO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Id não pode ser vazio.
        /// </summary>
        internal static string CODIGO_ERRO_VAZIO {
            get {
                return ResourceManager.GetString("CODIGO_ERRO_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        internal static string COMBOBOX_ARTIGO_ATIVO {
            get {
                return ResourceManager.GetString("COMBOBOX_ARTIGO_ATIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inativo.
        /// </summary>
        internal static string COMBOBOX_ARTIGO_INATIVO {
            get {
                return ResourceManager.GetString("COMBOBOX_ARTIGO_INATIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição não pode ser vazia.
        /// </summary>
        internal static string DESCRICAO_ERRO_VAZIO {
            get {
                return ResourceManager.GetString("DESCRICAO_ERRO_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data inválida.
        /// </summary>
        internal static string ERRO_DATA_INVALIDA {
            get {
                return ResourceManager.GetString("ERRO_DATA_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O estado não pode ser vazio.
        /// </summary>
        internal static string ESTADO_ERRO_INVALIDO {
            get {
                return ResourceManager.GetString("ESTADO_ERRO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestão de Artigos.
        /// </summary>
        internal static string FORM_ARTIGO_TITLE {
            get {
                return ResourceManager.GetString("FORM_ARTIGO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Inicial.
        /// </summary>
        internal static string FORM_INICIAL_TITLE {
            get {
                return ResourceManager.GetString("FORM_INICIAL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre.
        /// </summary>
        internal static string FORM_SOBRE_TITLE {
            get {
                return ResourceManager.GetString("FORM_SOBRE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano lectivo.
        /// </summary>
        internal static string LABEL_ANO_LECTIVO {
            get {
                return ResourceManager.GetString("LABEL_ANO_LECTIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadeira.
        /// </summary>
        internal static string LABEL_CADEIRA {
            get {
                return ResourceManager.GetString("LABEL_CADEIRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Validade:.
        /// </summary>
        internal static string LABEL_DATA_VALIDADE {
            get {
                return ResourceManager.GetString("LABEL_DATA_VALIDADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição:.
        /// </summary>
        internal static string LABEL_DESCRICAO {
            get {
                return ResourceManager.GetString("LABEL_DESCRICAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desenvolvido por.
        /// </summary>
        internal static string LABEL_DESENVOLVIDO_POR {
            get {
                return ResourceManager.GetString("LABEL_DESENVOLVIDO_POR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado:.
        /// </summary>
        internal static string LABEL_ESTADO {
            get {
                return ResourceManager.GetString("LABEL_ESTADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestão de Artigos.
        /// </summary>
        internal static string LABEL_GESTAO {
            get {
                return ResourceManager.GetString("LABEL_GESTAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id:.
        /// </summary>
        internal static string LABEL_ID {
            get {
                return ResourceManager.GetString("LABEL_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listagem de Artigos.
        /// </summary>
        internal static string LABEL_LISTAGEM {
            get {
                return ResourceManager.GetString("LABEL_LISTAGEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesa.
        /// </summary>
        internal static string LABEL_MESA {
            get {
                return ResourceManager.GetString("LABEL_MESA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Móvel.
        /// </summary>
        internal static string LABEL_MOVEL {
            get {
                return ResourceManager.GetString("LABEL_MOVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preço:.
        /// </summary>
        internal static string LABEL_PRECO {
            get {
                return ResourceManager.GetString("LABEL_PRECO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Artigo:.
        /// </summary>
        internal static string LABEL_TIPO_ARTIGO {
            get {
                return ResourceManager.GetString("LABEL_TIPO_ARTIGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total de Artigos:.
        /// </summary>
        internal static string LABEL_TOTAL_ARTIGOS {
            get {
                return ResourceManager.GetString("LABEL_TOTAL_ARTIGOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preço inválido.
        /// </summary>
        internal static string PRECO_ERRO_INVALIDO {
            get {
                return ResourceManager.GetString("PRECO_ERRO_INVALIDO", resourceCulture);
            }
        }
    }
}
